"""Unit tests for Studio Infrastructure Generator."""
from __future__ import annotations

import pytest

from app.studio.ai_generator import generate_ai_manifest
from app.studio.backend_generator import generate_backend_manifest
from app.studio.composer import compose_modules
from app.studio.frontend_generator import generate_frontend_manifest
from app.studio.infrastructure_generator import (
    DEPLOYMENT_TARGETS,
    estimate_infra_cost,
    generate_deployment_targets,
    generate_environment,
    generate_env_example,
    generate_infrastructure_manifest,
    security_review,
)
from app.studio.schemas import ProductBlueprint


def _hospital_blueprint() -> ProductBlueprint:
    return ProductBlueprint(
        industry="healthcare",
        product_type="saas",
        pages=["Landing", "Login", "Admin", "Patients", "Appointments", "Billing", "Dashboard"],
        dashboard_modules=["Schedule"],
        backend_modules=["Auth", "Billing", "AI Gateway", "Knowledge", "Storage", "Appointments"],
        database_tables=["users", "patients", "appointments"],
        roles=["admin", "doctor"],
        authentication={"jwt": True, "rbac": True},
        billing={"enabled": True},
        payments={"providers": ["razorpay"]},
        ai_features=["chat", "rag", "appointment_assistant", "memory"],
        knowledge={"enabled": True, "rag": True},
        workflows=["appointment_booking", "human_handoff"],
        integrations=["email", "storage", "widget"],
        deployment={"targets": ["docker", "vps"], "ssl": True},
        marketplace_category="saas",
        estimated_complexity="high",
    )


def _pipeline():
    bp = _hospital_blueprint()
    modules = compose_modules(bp)
    frontend = generate_frontend_manifest(
        blueprint=bp,
        modules=modules,
        project_title="Hospital",
        blueprint_version=1,
        build_plan_version=1,
    )
    backend = generate_backend_manifest(
        blueprint=bp,
        modules=modules,
        frontend=frontend,
        project_title="Hospital",
        blueprint_version=1,
        build_plan_version=1,
        frontend_version=1,
    )
    ai = generate_ai_manifest(
        blueprint=bp,
        modules=modules,
        backend=backend,
        project_title="Hospital Ops",
        blueprint_version=1,
        build_plan_version=1,
        frontend_version=1,
        backend_version=1,
    )
    return bp, modules, backend, ai


@pytest.mark.unit
def test_infrastructure_manifest_reuses_platform_stack():
    bp, modules, backend, ai = _pipeline()
    manifest = generate_infrastructure_manifest(
        blueprint=bp,
        modules=modules,
        backend=backend,
        ai=ai,
        project_title="Hospital Ops",
        blueprint_version=1,
        build_plan_version=1,
        frontend_version=1,
        backend_version=1,
        ai_version=1,
    )
    ids = {c.id for c in manifest.components}
    for required in (
        "docker",
        "compose",
        "nginx",
        "postgres",
        "redis",
        "workers",
        "scheduler",
        "healthchecks",
        "logging",
        "monitoring",
        "metrics",
        "tracing",
        "backups",
        "restore",
        "scaling",
        "rate_limiting",
        "cdn",
        "storage",
        "env_secrets",
    ):
        assert required in ids
    assert all(c.reuse for c in manifest.components if c.id != "cdn")
    assert "docker-compose.prod.yml" in str(manifest.runtime.get("compose"))
    assert "does not deploy" in manifest.note.lower() or "planning only" in manifest.note.lower()
    assert manifest.summary.reuse_percent >= 90
    assert "ai_gateway" in manifest.runtime


@pytest.mark.unit
def test_environment_generation_and_example():
    bp, modules, backend, ai = _pipeline()
    envs = generate_environment(bp, modules, ai, backend)
    keys = {e.key for e in envs}
    assert "JWT_SECRET_KEY" in keys
    assert "DB_PASSWORD" in keys
    assert "OPENAI_API_KEY" in keys
    assert any(e.group == "payments" for e in envs)
    assert any(e.group == "email" for e in envs)
    assert any(e.group == "analytics" for e in envs)
    example = generate_env_example(envs)
    assert "JWT_SECRET_KEY=" in example
    assert "REQUIRED" in example
    assert example.startswith("# Generated by THTWAAT Studio Phase 7")


@pytest.mark.unit
def test_security_validation_warnings():
    weak = ProductBlueprint(
        industry="general",
        product_type="saas",
        authentication={},
        deployment={"targets": ["docker"]},
        estimated_complexity="low",
    )
    bp, modules, backend, ai = _pipeline()
    components = generate_infrastructure_manifest(
        blueprint=bp,
        modules=modules,
        backend=backend,
        ai=ai,
        project_title="Hospital",
        blueprint_version=1,
        build_plan_version=1,
        frontend_version=1,
        backend_version=1,
        ai_version=1,
    ).components
    envs = generate_environment(weak, modules, ai, backend)
    targets = generate_deployment_targets(weak)
    warnings = security_review(
        blueprint=weak, components=components, envs=envs, targets=targets
    )
    codes = {w.code for w in warnings}
    assert "infra_weak_auth" in codes
    assert "infra_open_ports" in codes
    assert "infra_secrets_required" in codes


@pytest.mark.unit
def test_cost_estimation():
    bp, modules, backend, ai = _pipeline()
    components = generate_infrastructure_manifest(
        blueprint=bp,
        modules=modules,
        backend=backend,
        ai=ai,
        project_title="Hospital",
        blueprint_version=1,
        build_plan_version=1,
        frontend_version=1,
        backend_version=1,
        ai_version=1,
    ).components
    cost = estimate_infra_cost(blueprint=bp, ai=ai, components=components)
    assert cost.monthly_total_usd > 0
    assert cost.infrastructure_usd > 0
    assert cost.storage_usd > 0
    assert cost.bandwidth_usd > 0
    assert cost.ai_usd == ai.cost.estimated_monthly_usd
    assert abs(
        cost.monthly_total_usd
        - (cost.infrastructure_usd + cost.ai_usd + cost.storage_usd + cost.bandwidth_usd)
    ) < 0.01


@pytest.mark.unit
def test_deployment_planning_targets():
    bp = _hospital_blueprint()
    targets = generate_deployment_targets(bp)
    ids = {t.id for t in targets}
    for name in DEPLOYMENT_TARGETS:
        assert name in ids
    assert all(t.planning_only for t in targets)
    docker = next(t for t in targets if t.id == "docker")
    vps = next(t for t in targets if t.id == "vps")
    assert docker.recommended and vps.recommended
    assert docker.reuse_existing_stack
    assert docker.score >= vps.score or docker.recommended
