"""feat(products): add products table for enterprise product platform

Revision ID: 47f16c654a2b
Revises: eee894a42373
Create Date: 2026-07-13 09:51:30.096561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47f16c654a2b'
down_revision: Union[str, Sequence[str], None] = 'eee894a42373'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
