"""feat(notifications): add notifications table

Revision ID: 9f6a5a4ac0f7
Revises: bee300a130da
Create Date: 2026-07-13 02:35:31.600982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f6a5a4ac0f7'
down_revision: Union[str, Sequence[str], None] = 'bee300a130da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
