"""feat(storage): add storage_files table

Revision ID: bee300a130da
Revises: 04f356bc6367
Create Date: 2026-07-13 02:15:09.200565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bee300a130da'
down_revision: Union[str, Sequence[str], None] = '04f356bc6367'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('storage_files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('storage_filename', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('extension', sa.String(length=20), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('provider', sa.Enum('LOCAL', 'S3', 'MINIO', name='storage_provider_enum'), nullable=False),
    sa.Column('storage_path', sa.String(length=1024), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_storage_files_company_id'), 'storage_files', ['company_id'], unique=False)
    op.create_index(op.f('ix_storage_files_id'), 'storage_files', ['id'], unique=False)
    op.create_index(op.f('ix_storage_files_storage_filename'), 'storage_files', ['storage_filename'], unique=True)
    op.create_index(op.f('ix_storage_files_user_id'), 'storage_files', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_storage_files_user_id'), table_name='storage_files')
    op.drop_index(op.f('ix_storage_files_storage_filename'), table_name='storage_files')
    op.drop_index(op.f('ix_storage_files_id'), table_name='storage_files')
    op.drop_index(op.f('ix_storage_files_company_id'), table_name='storage_files')
    op.drop_table('storage_files')
    # ### end Alembic commands ###
