"""Add MFASettings

Revision ID: e534b4dfff0f
Revises: 13ece7f349ea
Create Date: 2026-07-14 06:15:27.851886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e534b4dfff0f'
down_revision: Union[str, Sequence[str], None] = '13ece7f349ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mfa_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('secret', sa.String(length=255), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('backup_codes', sa.String(), nullable=True),
    sa.Column('trusted_devices', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mfa_settings_id'), 'mfa_settings', ['id'], unique=False)
    op.create_index(op.f('ix_mfa_settings_user_id'), 'mfa_settings', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mfa_settings_user_id'), table_name='mfa_settings')
    op.drop_index(op.f('ix_mfa_settings_id'), table_name='mfa_settings')
    op.drop_table('mfa_settings')
    # ### end Alembic commands ###
