"""feat(ai): add app_id and credits_balance

Revision ID: ea19cfa6cfd2
Revises: e534b4dfff0f
Create Date: 2026-07-14 21:05:19.399298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea19cfa6cfd2'
down_revision: Union[str, Sequence[str], None] = 'e534b4dfff0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_requests', sa.Column('app_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_ai_requests_app_id'), 'ai_requests', ['app_id'], unique=False)
    op.create_foreign_key(None, 'ai_requests', 'apps', ['app_id'], ['id'], ondelete='SET NULL')
    op.add_column('companies', sa.Column('credits_balance', sa.Numeric(precision=10, scale=4), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'credits_balance')
    op.drop_constraint(None, 'ai_requests', type_='foreignkey')
    op.drop_index(op.f('ix_ai_requests_app_id'), table_name='ai_requests')
    op.drop_column('ai_requests', 'app_id')
    # ### end Alembic commands ###
