"""feat(ai): add ai_requests table for enterprise gateway

Revision ID: eee894a42373
Revises: f2df6fa73a82
Create Date: 2026-07-13 09:40:44.364283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eee894a42373'
down_revision: Union[str, Sequence[str], None] = 'f2df6fa73a82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
