"""feat(payments): add payments table

Revision ID: f2df6fa73a82
Revises: 9f6a5a4ac0f7
Create Date: 2026-07-13 02:48:23.462558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2df6fa73a82'
down_revision: Union[str, Sequence[str], None] = '9f6a5a4ac0f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
