-- AUTO-GENERATED by scripts/generate_marketplace_seed_sql.py
-- Generated: 2026-08-04T01:45:36Z
-- Templates: 12 (package)
-- Requires migration d0e1f2a3b4c5 (kind, pricing_tier, expanded categories).
-- Idempotent: ON CONFLICT upserts. Safe to re-run.
BEGIN;

-- Package catalog rows
INSERT INTO marketplace_templates (
  id, slug, name, category, kind, pricing_tier, industry, description, version,
  thumbnail, icon, tags, author, status, price, is_public, is_featured,
  supports_agents, supports_domains, supports_billing, supports_mobile,
  package_path, install_count, default_config, created_at, updated_at
) VALUES (
  '13612b59-e106-518d-9d6c-f1394612b33a'::uuid,
  'ai-website-starter',
  'AI Website Starter',
  'website'::template_category_enum,
  'package'::template_kind_enum,
  'free'::template_pricing_tier_enum,
  'general',
  'Multi-page AI website with chat, knowledge search, blog, and lead capture.',
  '1.0.0',
  '/templates/website.png',
  'globe',
  ARRAY['website', 'seo', 'chat', 'leads', 'package']::text[],
  'THTWAAT',
  'published'::template_status_enum,
  0,
  TRUE,
  TRUE,
  TRUE, TRUE, FALSE, FALSE,
  'apps/templates/website',
  0,
  '{"stack":["nextjs15","tailwind","shadcn"],"env":["NEXT_PUBLIC_API_URL","NEXT_PUBLIC_AGENT_API_KEY"],"pages":["home","about","services","pricing","blog","contact","chat"],"features":["widget","streaming_chat","knowledge_search","leads"]}'::jsonb,
  NOW(), NOW()
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  kind = EXCLUDED.kind,
  pricing_tier = EXCLUDED.pricing_tier,
  industry = EXCLUDED.industry,
  description = EXCLUDED.description,
  thumbnail = EXCLUDED.thumbnail,
  icon = EXCLUDED.icon,
  tags = EXCLUDED.tags,
  author = EXCLUDED.author,
  status = EXCLUDED.status,
  is_public = EXCLUDED.is_public,
  is_featured = EXCLUDED.is_featured,
  supports_agents = EXCLUDED.supports_agents,
  supports_domains = EXCLUDED.supports_domains,
  supports_billing = EXCLUDED.supports_billing,
  supports_mobile = EXCLUDED.supports_mobile,
  package_path = EXCLUDED.package_path,
  default_config = EXCLUDED.default_config,
  updated_at = NOW()
  -- note: version column updated only by upgrade script / version insert
;
INSERT INTO marketplace_template_versions (
  id, template_id, version, changelog, config, is_latest, published_at, created_at, updated_at
) VALUES (
  gen_random_uuid(),
  '13612b59-e106-518d-9d6c-f1394612b33a'::uuid,
  '1.0.0',
  'Initial Website Starter release',
  '{"stack":["nextjs15","tailwind","shadcn"],"env":["NEXT_PUBLIC_API_URL","NEXT_PUBLIC_AGENT_API_KEY"],"pages":["home","about","services","pricing","blog","contact","chat"],"features":["widget","streaming_chat","knowledge_search","leads"]}'::jsonb,
  TRUE,
  NOW(),
  NOW(),
  NOW()
)
ON CONFLICT (template_id, version) DO UPDATE SET
  changelog = EXCLUDED.changelog,
  config = EXCLUDED.config,
  is_latest = TRUE,
  published_at = COALESCE(marketplace_template_versions.published_at, NOW()),
  updated_at = NOW();

UPDATE marketplace_templates
SET version = '1.0.0',
    default_config = '{"stack":["nextjs15","tailwind","shadcn"],"env":["NEXT_PUBLIC_API_URL","NEXT_PUBLIC_AGENT_API_KEY"],"pages":["home","about","services","pricing","blog","contact","chat"],"features":["widget","streaming_chat","knowledge_search","leads"]}'::jsonb,
    updated_at = NOW()
WHERE id = '13612b59-e106-518d-9d6c-f1394612b33a'::uuid;
INSERT INTO marketplace_templates (
  id, slug, name, category, kind, pricing_tier, industry, description, version,
  thumbnail, icon, tags, author, status, price, is_public, is_featured,
  supports_agents, supports_domains, supports_billing, supports_mobile,
  package_path, install_count, default_config, created_at, updated_at
) VALUES (
  '9c83f7bb-9e02-5419-94be-9dc54e128e9b'::uuid,
  'ecommerce-starter',
  'Ecommerce Starter',
  'ecommerce'::template_category_enum,
  'package'::template_kind_enum,
  'free'::template_pricing_tier_enum,
  'ecommerce',
  'AI-assisted ecommerce storefront with catalog, cart flows, and shopping assistant.',
  '1.0.0',
  '/templates/ecommerce.png',
  'shopping-bag',
  ARRAY['ecommerce', 'shop', 'catalog', 'chat', 'package']::text[],
  'THTWAAT',
  'published'::template_status_enum,
  0,
  TRUE,
  TRUE,
  TRUE, TRUE, TRUE, FALSE,
  'apps/templates/website',
  0,
  '{"stack":["nextjs15","tailwind","shadcn"],"env":["NEXT_PUBLIC_API_URL","NEXT_PUBLIC_AGENT_API_KEY"],"pages":["home","shop","product","cart","checkout","account","chat"],"features":["widget","streaming_chat","catalog","leads","payments"]}'::jsonb,
  NOW(), NOW()
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  kind = EXCLUDED.kind,
  pricing_tier = EXCLUDED.pricing_tier,
  industry = EXCLUDED.industry,
  description = EXCLUDED.description,
  thumbnail = EXCLUDED.thumbnail,
  icon = EXCLUDED.icon,
  tags = EXCLUDED.tags,
  author = EXCLUDED.author,
  status = EXCLUDED.status,
  is_public = EXCLUDED.is_public,
  is_featured = EXCLUDED.is_featured,
  supports_agents = EXCLUDED.supports_agents,
  supports_domains = EXCLUDED.supports_domains,
  supports_billing = EXCLUDED.supports_billing,
  supports_mobile = EXCLUDED.supports_mobile,
  package_path = EXCLUDED.package_path,
  default_config = EXCLUDED.default_config,
  updated_at = NOW()
  -- note: version column updated only by upgrade script / version insert
;
INSERT INTO marketplace_template_versions (
  id, template_id, version, changelog, config, is_latest, published_at, created_at, updated_at
) VALUES (
  gen_random_uuid(),
  '9c83f7bb-9e02-5419-94be-9dc54e128e9b'::uuid,
  '1.0.0',
  'Initial Ecommerce Starter release',
  '{"stack":["nextjs15","tailwind","shadcn"],"env":["NEXT_PUBLIC_API_URL","NEXT_PUBLIC_AGENT_API_KEY"],"pages":["home","shop","product","cart","checkout","account","chat"],"features":["widget","streaming_chat","catalog","leads","payments"]}'::jsonb,
  TRUE,
  NOW(),
  NOW(),
  NOW()
)
ON CONFLICT (template_id, version) DO UPDATE SET
  changelog = EXCLUDED.changelog,
  config = EXCLUDED.config,
  is_latest = TRUE,
  published_at = COALESCE(marketplace_template_versions.published_at, NOW()),
  updated_at = NOW();

UPDATE marketplace_templates
SET version = '1.0.0',
    default_config = '{"stack":["nextjs15","tailwind","shadcn"],"env":["NEXT_PUBLIC_API_URL","NEXT_PUBLIC_AGENT_API_KEY"],"pages":["home","shop","product","cart","checkout","account","chat"],"features":["widget","streaming_chat","catalog","leads","payments"]}'::jsonb,
    updated_at = NOW()
WHERE id = '9c83f7bb-9e02-5419-94be-9dc54e128e9b'::uuid;
INSERT INTO marketplace_templates (
  id, slug, name, category, kind, pricing_tier, industry, description, version,
  thumbnail, icon, tags, author, status, price, is_public, is_featured,
  supports_agents, supports_domains, supports_billing, supports_mobile,
  package_path, install_count, default_config, created_at, updated_at
) VALUES (
  'c7d0f642-b3e9-5be5-9f1d-d760a03017f1'::uuid,
  'hotel-website-starter',
  'Hotel Website Starter',
  'website'::template_category_enum,
  'package'::template_kind_enum,
  'free'::template_pricing_tier_enum,
  'hotel',
  'Hospitality website with AI concierge, room enquiry, and booking prompts.',
  '1.0.0',
  '/templates/hotel.png',
  'hotel',
  ARRAY['hotel', 'hospitality', 'booking', 'website', 'package']::text[],
  'THTWAAT',
  'published'::template_status_enum,
  0,
  TRUE,
  TRUE,
  TRUE, TRUE, TRUE, FALSE,
  'apps/templates/website',
  0,
  '{"stack":["nextjs15","tailwind","shadcn"],"env":["NEXT_PUBLIC_API_URL","NEXT_PUBLIC_AGENT_API_KEY"],"pages":["home","rooms","amenities","dining","offers","contact","chat"],"features":["widget","streaming_chat","booking","leads","knowledge"]}'::jsonb,
  NOW(), NOW()
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  kind = EXCLUDED.kind,
  pricing_tier = EXCLUDED.pricing_tier,
  industry = EXCLUDED.industry,
  description = EXCLUDED.description,
  thumbnail = EXCLUDED.thumbnail,
  icon = EXCLUDED.icon,
  tags = EXCLUDED.tags,
  author = EXCLUDED.author,
  status = EXCLUDED.status,
  is_public = EXCLUDED.is_public,
  is_featured = EXCLUDED.is_featured,
  supports_agents = EXCLUDED.supports_agents,
  supports_domains = EXCLUDED.supports_domains,
  supports_billing = EXCLUDED.supports_billing,
  supports_mobile = EXCLUDED.supports_mobile,
  package_path = EXCLUDED.package_path,
  default_config = EXCLUDED.default_config,
  updated_at = NOW()
  -- note: version column updated only by upgrade script / version insert
;
INSERT INTO marketplace_template_versions (
  id, template_id, version, changelog, config, is_latest, published_at, created_at, updated_at
) VALUES (
  gen_random_uuid(),
  'c7d0f642-b3e9-5be5-9f1d-d760a03017f1'::uuid,
  '1.0.0',
  'Initial Hotel Website Starter release',
  '{"stack":["nextjs15","tailwind","shadcn"],"env":["NEXT_PUBLIC_API_URL","NEXT_PUBLIC_AGENT_API_KEY"],"pages":["home","rooms","amenities","dining","offers","contact","chat"],"features":["widget","streaming_chat","booking","leads","knowledge"]}'::jsonb,
  TRUE,
  NOW(),
  NOW(),
  NOW()
)
ON CONFLICT (template_id, version) DO UPDATE SET
  changelog = EXCLUDED.changelog,
  config = EXCLUDED.config,
  is_latest = TRUE,
  published_at = COALESCE(marketplace_template_versions.published_at, NOW()),
  updated_at = NOW();

UPDATE marketplace_templates
SET version = '1.0.0',
    default_config = '{"stack":["nextjs15","tailwind","shadcn"],"env":["NEXT_PUBLIC_API_URL","NEXT_PUBLIC_AGENT_API_KEY"],"pages":["home","rooms","amenities","dining","offers","contact","chat"],"features":["widget","streaming_chat","booking","leads","knowledge"]}'::jsonb,
    updated_at = NOW()
WHERE id = 'c7d0f642-b3e9-5be5-9f1d-d760a03017f1'::uuid;
INSERT INTO marketplace_templates (
  id, slug, name, category, kind, pricing_tier, industry, description, version,
  thumbnail, icon, tags, author, status, price, is_public, is_featured,
  supports_agents, supports_domains, supports_billing, supports_mobile,
  package_path, install_count, default_config, created_at, updated_at
) VALUES (
  'abae812e-931c-5b03-90fd-d680f766b587'::uuid,
  'restaurant-starter',
  'Restaurant Starter',
  'restaurant'::template_category_enum,
  'package'::template_kind_enum,
  'free'::template_pricing_tier_enum,
  'restaurant',
  'Restaurant website with AI menu assistant, ordering, and table booking.',
  '1.0.0',
  '/templates/restaurant.png',
  'utensils',
  ARRAY['restaurant', 'menu', 'ordering', 'booking', 'package']::text[],
  'THTWAAT',
  'published'::template_status_enum,
  0,
  TRUE,
  TRUE,
  TRUE, TRUE, TRUE, FALSE,
  'apps/templates/website',
  0,
  '{"stack":["nextjs15","tailwind","shadcn"],"env":["NEXT_PUBLIC_API_URL","NEXT_PUBLIC_AGENT_API_KEY"],"pages":["home","menu","reservations","about","contact","chat"],"features":["widget","streaming_chat","ordering","booking","leads"]}'::jsonb,
  NOW(), NOW()
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  kind = EXCLUDED.kind,
  pricing_tier = EXCLUDED.pricing_tier,
  industry = EXCLUDED.industry,
  description = EXCLUDED.description,
  thumbnail = EXCLUDED.thumbnail,
  icon = EXCLUDED.icon,
  tags = EXCLUDED.tags,
  author = EXCLUDED.author,
  status = EXCLUDED.status,
  is_public = EXCLUDED.is_public,
  is_featured = EXCLUDED.is_featured,
  supports_agents = EXCLUDED.supports_agents,
  supports_domains = EXCLUDED.supports_domains,
  supports_billing = EXCLUDED.supports_billing,
  supports_mobile = EXCLUDED.supports_mobile,
  package_path = EXCLUDED.package_path,
  default_config = EXCLUDED.default_config,
  updated_at = NOW()
  -- note: version column updated only by upgrade script / version insert
;
INSERT INTO marketplace_template_versions (
  id, template_id, version, changelog, config, is_latest, published_at, created_at, updated_at
) VALUES (
  gen_random_uuid(),
  'abae812e-931c-5b03-90fd-d680f766b587'::uuid,
  '1.0.0',
  'Initial Restaurant Starter release',
  '{"stack":["nextjs15","tailwind","shadcn"],"env":["NEXT_PUBLIC_API_URL","NEXT_PUBLIC_AGENT_API_KEY"],"pages":["home","menu","reservations","about","contact","chat"],"features":["widget","streaming_chat","ordering","booking","leads"]}'::jsonb,
  TRUE,
  NOW(),
  NOW(),
  NOW()
)
ON CONFLICT (template_id, version) DO UPDATE SET
  changelog = EXCLUDED.changelog,
  config = EXCLUDED.config,
  is_latest = TRUE,
  published_at = COALESCE(marketplace_template_versions.published_at, NOW()),
  updated_at = NOW();

UPDATE marketplace_templates
SET version = '1.0.0',
    default_config = '{"stack":["nextjs15","tailwind","shadcn"],"env":["NEXT_PUBLIC_API_URL","NEXT_PUBLIC_AGENT_API_KEY"],"pages":["home","menu","reservations","about","contact","chat"],"features":["widget","streaming_chat","ordering","booking","leads"]}'::jsonb,
    updated_at = NOW()
WHERE id = 'abae812e-931c-5b03-90fd-d680f766b587'::uuid;
INSERT INTO marketplace_templates (
  id, slug, name, category, kind, pricing_tier, industry, description, version,
  thumbnail, icon, tags, author, status, price, is_public, is_featured,
  supports_agents, supports_domains, supports_billing, supports_mobile,
  package_path, install_count, default_config, created_at, updated_at
) VALUES (
  'b90a85ba-ada6-5e5b-8f7c-5ff49b188c64'::uuid,
  'portfolio-starter',
  'Portfolio Starter',
  'website'::template_category_enum,
  'package'::template_kind_enum,
  'free'::template_pricing_tier_enum,
  'creative',
  'Personal or agency portfolio with AI project guide and lead capture.',
  '1.0.0',
  '/templates/portfolio.png',
  'briefcase',
  ARRAY['portfolio', 'creative', 'agency', 'website', 'package']::text[],
  'THTWAAT',
  'published'::template_status_enum,
  0,
  TRUE,
  FALSE,
  TRUE, TRUE, FALSE, FALSE,
  'apps/templates/website',
  0,
  '{"stack":["nextjs15","tailwind","shadcn"],"env":["NEXT_PUBLIC_API_URL","NEXT_PUBLIC_AGENT_API_KEY"],"pages":["home","work","about","services","contact","chat"],"features":["widget","streaming_chat","leads"]}'::jsonb,
  NOW(), NOW()
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  kind = EXCLUDED.kind,
  pricing_tier = EXCLUDED.pricing_tier,
  industry = EXCLUDED.industry,
  description = EXCLUDED.description,
  thumbnail = EXCLUDED.thumbnail,
  icon = EXCLUDED.icon,
  tags = EXCLUDED.tags,
  author = EXCLUDED.author,
  status = EXCLUDED.status,
  is_public = EXCLUDED.is_public,
  is_featured = EXCLUDED.is_featured,
  supports_agents = EXCLUDED.supports_agents,
  supports_domains = EXCLUDED.supports_domains,
  supports_billing = EXCLUDED.supports_billing,
  supports_mobile = EXCLUDED.supports_mobile,
  package_path = EXCLUDED.package_path,
  default_config = EXCLUDED.default_config,
  updated_at = NOW()
  -- note: version column updated only by upgrade script / version insert
;
INSERT INTO marketplace_template_versions (
  id, template_id, version, changelog, config, is_latest, published_at, created_at, updated_at
) VALUES (
  gen_random_uuid(),
  'b90a85ba-ada6-5e5b-8f7c-5ff49b188c64'::uuid,
  '1.0.0',
  'Initial Portfolio Starter release',
  '{"stack":["nextjs15","tailwind","shadcn"],"env":["NEXT_PUBLIC_API_URL","NEXT_PUBLIC_AGENT_API_KEY"],"pages":["home","work","about","services","contact","chat"],"features":["widget","streaming_chat","leads"]}'::jsonb,
  TRUE,
  NOW(),
  NOW(),
  NOW()
)
ON CONFLICT (template_id, version) DO UPDATE SET
  changelog = EXCLUDED.changelog,
  config = EXCLUDED.config,
  is_latest = TRUE,
  published_at = COALESCE(marketplace_template_versions.published_at, NOW()),
  updated_at = NOW();

UPDATE marketplace_templates
SET version = '1.0.0',
    default_config = '{"stack":["nextjs15","tailwind","shadcn"],"env":["NEXT_PUBLIC_API_URL","NEXT_PUBLIC_AGENT_API_KEY"],"pages":["home","work","about","services","contact","chat"],"features":["widget","streaming_chat","leads"]}'::jsonb,
    updated_at = NOW()
WHERE id = 'b90a85ba-ada6-5e5b-8f7c-5ff49b188c64'::uuid;
INSERT INTO marketplace_templates (
  id, slug, name, category, kind, pricing_tier, industry, description, version,
  thumbnail, icon, tags, author, status, price, is_public, is_featured,
  supports_agents, supports_domains, supports_billing, supports_mobile,
  package_path, install_count, default_config, created_at, updated_at
) VALUES (
  '17c6ef3f-e40f-5768-b9e5-eeb55c3c5f4a'::uuid,
  'blog-starter',
  'Blog Starter',
  'website'::template_category_enum,
  'package'::template_kind_enum,
  'free'::template_pricing_tier_enum,
  'content',
  'Content-first blog with AI writing assistant and knowledge search.',
  '1.0.0',
  '/templates/blog.png',
  'pen-line',
  ARRAY['blog', 'content', 'seo', 'website', 'package']::text[],
  'THTWAAT',
  'published'::template_status_enum,
  0,
  TRUE,
  FALSE,
  TRUE, TRUE, FALSE, FALSE,
  'apps/templates/website',
  0,
  '{"stack":["nextjs15","tailwind","shadcn"],"env":["NEXT_PUBLIC_API_URL","NEXT_PUBLIC_AGENT_API_KEY"],"pages":["home","blog","authors","topics","about","chat"],"features":["widget","streaming_chat","knowledge_search","leads"]}'::jsonb,
  NOW(), NOW()
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  kind = EXCLUDED.kind,
  pricing_tier = EXCLUDED.pricing_tier,
  industry = EXCLUDED.industry,
  description = EXCLUDED.description,
  thumbnail = EXCLUDED.thumbnail,
  icon = EXCLUDED.icon,
  tags = EXCLUDED.tags,
  author = EXCLUDED.author,
  status = EXCLUDED.status,
  is_public = EXCLUDED.is_public,
  is_featured = EXCLUDED.is_featured,
  supports_agents = EXCLUDED.supports_agents,
  supports_domains = EXCLUDED.supports_domains,
  supports_billing = EXCLUDED.supports_billing,
  supports_mobile = EXCLUDED.supports_mobile,
  package_path = EXCLUDED.package_path,
  default_config = EXCLUDED.default_config,
  updated_at = NOW()
  -- note: version column updated only by upgrade script / version insert
;
INSERT INTO marketplace_template_versions (
  id, template_id, version, changelog, config, is_latest, published_at, created_at, updated_at
) VALUES (
  gen_random_uuid(),
  '17c6ef3f-e40f-5768-b9e5-eeb55c3c5f4a'::uuid,
  '1.0.0',
  'Initial Blog Starter release',
  '{"stack":["nextjs15","tailwind","shadcn"],"env":["NEXT_PUBLIC_API_URL","NEXT_PUBLIC_AGENT_API_KEY"],"pages":["home","blog","authors","topics","about","chat"],"features":["widget","streaming_chat","knowledge_search","leads"]}'::jsonb,
  TRUE,
  NOW(),
  NOW(),
  NOW()
)
ON CONFLICT (template_id, version) DO UPDATE SET
  changelog = EXCLUDED.changelog,
  config = EXCLUDED.config,
  is_latest = TRUE,
  published_at = COALESCE(marketplace_template_versions.published_at, NOW()),
  updated_at = NOW();

UPDATE marketplace_templates
SET version = '1.0.0',
    default_config = '{"stack":["nextjs15","tailwind","shadcn"],"env":["NEXT_PUBLIC_API_URL","NEXT_PUBLIC_AGENT_API_KEY"],"pages":["home","blog","authors","topics","about","chat"],"features":["widget","streaming_chat","knowledge_search","leads"]}'::jsonb,
    updated_at = NOW()
WHERE id = '17c6ef3f-e40f-5768-b9e5-eeb55c3c5f4a'::uuid;
INSERT INTO marketplace_templates (
  id, slug, name, category, kind, pricing_tier, industry, description, version,
  thumbnail, icon, tags, author, status, price, is_public, is_featured,
  supports_agents, supports_domains, supports_billing, supports_mobile,
  package_path, install_count, default_config, created_at, updated_at
) VALUES (
  '48291637-cabe-5931-9f7d-3fd850510fab'::uuid,
  'saas-starter',
  'SaaS Starter',
  'saas'::template_category_enum,
  'package'::template_kind_enum,
  'free'::template_pricing_tier_enum,
  'b2b',
  'Full SaaS dashboard: auth, agents, knowledge, domains, billing, analytics.',
  '1.0.0',
  '/templates/saas.png',
  'layout-dashboard',
  ARRAY['saas', 'dashboard', 'billing', 'auth', 'package']::text[],
  'THTWAAT',
  'published'::template_status_enum,
  0,
  TRUE,
  TRUE,
  TRUE, TRUE, TRUE, FALSE,
  'apps/templates/saas',
  0,
  '{"stack":["nextjs15","tailwind","tanstack-query","rhf","zod"],"env":["NEXT_PUBLIC_API_URL","NEXT_PUBLIC_AGENT_API_KEY"],"modules":["auth","dashboard","agents","knowledge","domains","billing","analytics","settings","marketplace"],"features":["jwt","otp","usage_meter","publish"]}'::jsonb,
  NOW(), NOW()
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  kind = EXCLUDED.kind,
  pricing_tier = EXCLUDED.pricing_tier,
  industry = EXCLUDED.industry,
  description = EXCLUDED.description,
  thumbnail = EXCLUDED.thumbnail,
  icon = EXCLUDED.icon,
  tags = EXCLUDED.tags,
  author = EXCLUDED.author,
  status = EXCLUDED.status,
  is_public = EXCLUDED.is_public,
  is_featured = EXCLUDED.is_featured,
  supports_agents = EXCLUDED.supports_agents,
  supports_domains = EXCLUDED.supports_domains,
  supports_billing = EXCLUDED.supports_billing,
  supports_mobile = EXCLUDED.supports_mobile,
  package_path = EXCLUDED.package_path,
  default_config = EXCLUDED.default_config,
  updated_at = NOW()
  -- note: version column updated only by upgrade script / version insert
;
INSERT INTO marketplace_template_versions (
  id, template_id, version, changelog, config, is_latest, published_at, created_at, updated_at
) VALUES (
  gen_random_uuid(),
  '48291637-cabe-5931-9f7d-3fd850510fab'::uuid,
  '1.0.0',
  'Initial SaaS Starter release',
  '{"stack":["nextjs15","tailwind","tanstack-query","rhf","zod"],"env":["NEXT_PUBLIC_API_URL","NEXT_PUBLIC_AGENT_API_KEY"],"modules":["auth","dashboard","agents","knowledge","domains","billing","analytics","settings","marketplace"],"features":["jwt","otp","usage_meter","publish"]}'::jsonb,
  TRUE,
  NOW(),
  NOW(),
  NOW()
)
ON CONFLICT (template_id, version) DO UPDATE SET
  changelog = EXCLUDED.changelog,
  config = EXCLUDED.config,
  is_latest = TRUE,
  published_at = COALESCE(marketplace_template_versions.published_at, NOW()),
  updated_at = NOW();

UPDATE marketplace_templates
SET version = '1.0.0',
    default_config = '{"stack":["nextjs15","tailwind","tanstack-query","rhf","zod"],"env":["NEXT_PUBLIC_API_URL","NEXT_PUBLIC_AGENT_API_KEY"],"modules":["auth","dashboard","agents","knowledge","domains","billing","analytics","settings","marketplace"],"features":["jwt","otp","usage_meter","publish"]}'::jsonb,
    updated_at = NOW()
WHERE id = '48291637-cabe-5931-9f7d-3fd850510fab'::uuid;
INSERT INTO marketplace_templates (
  id, slug, name, category, kind, pricing_tier, industry, description, version,
  thumbnail, icon, tags, author, status, price, is_public, is_featured,
  supports_agents, supports_domains, supports_billing, supports_mobile,
  package_path, install_count, default_config, created_at, updated_at
) VALUES (
  'e5e0294c-8b8e-5109-b043-74ae80f47264'::uuid,
  'crm-starter',
  'CRM Starter',
  'crm'::template_category_enum,
  'package'::template_kind_enum,
  'free'::template_pricing_tier_enum,
  'crm',
  'CRM-oriented SaaS shell with pipeline, contacts, and AI sales assistant.',
  '1.0.0',
  '/templates/crm.png',
  'contact',
  ARRAY['crm', 'sales', 'pipeline', 'saas', 'package']::text[],
  'THTWAAT',
  'published'::template_status_enum,
  0,
  TRUE,
  TRUE,
  TRUE, TRUE, TRUE, FALSE,
  'apps/templates/saas',
  0,
  '{"stack":["nextjs15","tailwind","tanstack-query"],"env":["NEXT_PUBLIC_API_URL","NEXT_PUBLIC_AGENT_API_KEY"],"modules":["pipeline","contacts","deals","agents","knowledge","settings"],"features":["widget","streaming_chat","leads","usage_meter"]}'::jsonb,
  NOW(), NOW()
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  kind = EXCLUDED.kind,
  pricing_tier = EXCLUDED.pricing_tier,
  industry = EXCLUDED.industry,
  description = EXCLUDED.description,
  thumbnail = EXCLUDED.thumbnail,
  icon = EXCLUDED.icon,
  tags = EXCLUDED.tags,
  author = EXCLUDED.author,
  status = EXCLUDED.status,
  is_public = EXCLUDED.is_public,
  is_featured = EXCLUDED.is_featured,
  supports_agents = EXCLUDED.supports_agents,
  supports_domains = EXCLUDED.supports_domains,
  supports_billing = EXCLUDED.supports_billing,
  supports_mobile = EXCLUDED.supports_mobile,
  package_path = EXCLUDED.package_path,
  default_config = EXCLUDED.default_config,
  updated_at = NOW()
  -- note: version column updated only by upgrade script / version insert
;
INSERT INTO marketplace_template_versions (
  id, template_id, version, changelog, config, is_latest, published_at, created_at, updated_at
) VALUES (
  gen_random_uuid(),
  'e5e0294c-8b8e-5109-b043-74ae80f47264'::uuid,
  '1.0.0',
  'Initial CRM Starter release',
  '{"stack":["nextjs15","tailwind","tanstack-query"],"env":["NEXT_PUBLIC_API_URL","NEXT_PUBLIC_AGENT_API_KEY"],"modules":["pipeline","contacts","deals","agents","knowledge","settings"],"features":["widget","streaming_chat","leads","usage_meter"]}'::jsonb,
  TRUE,
  NOW(),
  NOW(),
  NOW()
)
ON CONFLICT (template_id, version) DO UPDATE SET
  changelog = EXCLUDED.changelog,
  config = EXCLUDED.config,
  is_latest = TRUE,
  published_at = COALESCE(marketplace_template_versions.published_at, NOW()),
  updated_at = NOW();

UPDATE marketplace_templates
SET version = '1.0.0',
    default_config = '{"stack":["nextjs15","tailwind","tanstack-query"],"env":["NEXT_PUBLIC_API_URL","NEXT_PUBLIC_AGENT_API_KEY"],"modules":["pipeline","contacts","deals","agents","knowledge","settings"],"features":["widget","streaming_chat","leads","usage_meter"]}'::jsonb,
    updated_at = NOW()
WHERE id = 'e5e0294c-8b8e-5109-b043-74ae80f47264'::uuid;
INSERT INTO marketplace_templates (
  id, slug, name, category, kind, pricing_tier, industry, description, version,
  thumbnail, icon, tags, author, status, price, is_public, is_featured,
  supports_agents, supports_domains, supports_billing, supports_mobile,
  package_path, install_count, default_config, created_at, updated_at
) VALUES (
  '170835ca-adce-5eea-baf1-975233a820d4'::uuid,
  'documentation-site',
  'Documentation Site',
  'website'::template_category_enum,
  'package'::template_kind_enum,
  'free'::template_pricing_tier_enum,
  'developer',
  'Developer docs site with AI search over knowledge bases and API guides.',
  '1.0.0',
  '/templates/docs.png',
  'book-open',
  ARRAY['docs', 'documentation', 'developer', 'website', 'package']::text[],
  'THTWAAT',
  'published'::template_status_enum,
  0,
  TRUE,
  FALSE,
  TRUE, TRUE, FALSE, FALSE,
  'apps/templates/website',
  0,
  '{"stack":["nextjs15","tailwind","mdx"],"env":["NEXT_PUBLIC_API_URL","NEXT_PUBLIC_AGENT_API_KEY"],"pages":["home","docs","guides","api","changelog","chat"],"features":["widget","streaming_chat","knowledge_search"]}'::jsonb,
  NOW(), NOW()
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  kind = EXCLUDED.kind,
  pricing_tier = EXCLUDED.pricing_tier,
  industry = EXCLUDED.industry,
  description = EXCLUDED.description,
  thumbnail = EXCLUDED.thumbnail,
  icon = EXCLUDED.icon,
  tags = EXCLUDED.tags,
  author = EXCLUDED.author,
  status = EXCLUDED.status,
  is_public = EXCLUDED.is_public,
  is_featured = EXCLUDED.is_featured,
  supports_agents = EXCLUDED.supports_agents,
  supports_domains = EXCLUDED.supports_domains,
  supports_billing = EXCLUDED.supports_billing,
  supports_mobile = EXCLUDED.supports_mobile,
  package_path = EXCLUDED.package_path,
  default_config = EXCLUDED.default_config,
  updated_at = NOW()
  -- note: version column updated only by upgrade script / version insert
;
INSERT INTO marketplace_template_versions (
  id, template_id, version, changelog, config, is_latest, published_at, created_at, updated_at
) VALUES (
  gen_random_uuid(),
  '170835ca-adce-5eea-baf1-975233a820d4'::uuid,
  '1.0.0',
  'Initial Documentation Site release',
  '{"stack":["nextjs15","tailwind","mdx"],"env":["NEXT_PUBLIC_API_URL","NEXT_PUBLIC_AGENT_API_KEY"],"pages":["home","docs","guides","api","changelog","chat"],"features":["widget","streaming_chat","knowledge_search"]}'::jsonb,
  TRUE,
  NOW(),
  NOW(),
  NOW()
)
ON CONFLICT (template_id, version) DO UPDATE SET
  changelog = EXCLUDED.changelog,
  config = EXCLUDED.config,
  is_latest = TRUE,
  published_at = COALESCE(marketplace_template_versions.published_at, NOW()),
  updated_at = NOW();

UPDATE marketplace_templates
SET version = '1.0.0',
    default_config = '{"stack":["nextjs15","tailwind","mdx"],"env":["NEXT_PUBLIC_API_URL","NEXT_PUBLIC_AGENT_API_KEY"],"pages":["home","docs","guides","api","changelog","chat"],"features":["widget","streaming_chat","knowledge_search"]}'::jsonb,
    updated_at = NOW()
WHERE id = '170835ca-adce-5eea-baf1-975233a820d4'::uuid;
INSERT INTO marketplace_templates (
  id, slug, name, category, kind, pricing_tier, industry, description, version,
  thumbnail, icon, tags, author, status, price, is_public, is_featured,
  supports_agents, supports_domains, supports_billing, supports_mobile,
  package_path, install_count, default_config, created_at, updated_at
) VALUES (
  '074fc39c-f6ba-50a7-90da-f0fccfc4a20b'::uuid,
  'landing-page-starter',
  'Landing Page Starter',
  'landing'::template_category_enum,
  'package'::template_kind_enum,
  'free'::template_pricing_tier_enum,
  'growth',
  'High-converting single-page landing with inline AI assistant and demo booking.',
  '1.0.0',
  '/templates/landing.png',
  'sparkles',
  ARRAY['landing', 'conversion', 'demo', 'faq', 'package']::text[],
  'THTWAAT',
  'published'::template_status_enum,
  0,
  TRUE,
  TRUE,
  TRUE, TRUE, TRUE, FALSE,
  'apps/templates/landing',
  0,
  '{"stack":["nextjs15","tailwind","shadcn"],"env":["NEXT_PUBLIC_API_URL","NEXT_PUBLIC_AGENT_API_KEY"],"sections":["hero","ai_chat_cta","features","benefits","pricing","testimonials","faq","book_demo","contact"],"features":["widget","inline_assistant","streaming","leads"]}'::jsonb,
  NOW(), NOW()
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  kind = EXCLUDED.kind,
  pricing_tier = EXCLUDED.pricing_tier,
  industry = EXCLUDED.industry,
  description = EXCLUDED.description,
  thumbnail = EXCLUDED.thumbnail,
  icon = EXCLUDED.icon,
  tags = EXCLUDED.tags,
  author = EXCLUDED.author,
  status = EXCLUDED.status,
  is_public = EXCLUDED.is_public,
  is_featured = EXCLUDED.is_featured,
  supports_agents = EXCLUDED.supports_agents,
  supports_domains = EXCLUDED.supports_domains,
  supports_billing = EXCLUDED.supports_billing,
  supports_mobile = EXCLUDED.supports_mobile,
  package_path = EXCLUDED.package_path,
  default_config = EXCLUDED.default_config,
  updated_at = NOW()
  -- note: version column updated only by upgrade script / version insert
;
INSERT INTO marketplace_template_versions (
  id, template_id, version, changelog, config, is_latest, published_at, created_at, updated_at
) VALUES (
  gen_random_uuid(),
  '074fc39c-f6ba-50a7-90da-f0fccfc4a20b'::uuid,
  '1.0.0',
  'Initial Landing Page Starter release',
  '{"stack":["nextjs15","tailwind","shadcn"],"env":["NEXT_PUBLIC_API_URL","NEXT_PUBLIC_AGENT_API_KEY"],"sections":["hero","ai_chat_cta","features","benefits","pricing","testimonials","faq","book_demo","contact"],"features":["widget","inline_assistant","streaming","leads"]}'::jsonb,
  TRUE,
  NOW(),
  NOW(),
  NOW()
)
ON CONFLICT (template_id, version) DO UPDATE SET
  changelog = EXCLUDED.changelog,
  config = EXCLUDED.config,
  is_latest = TRUE,
  published_at = COALESCE(marketplace_template_versions.published_at, NOW()),
  updated_at = NOW();

UPDATE marketplace_templates
SET version = '1.0.0',
    default_config = '{"stack":["nextjs15","tailwind","shadcn"],"env":["NEXT_PUBLIC_API_URL","NEXT_PUBLIC_AGENT_API_KEY"],"sections":["hero","ai_chat_cta","features","benefits","pricing","testimonials","faq","book_demo","contact"],"features":["widget","inline_assistant","streaming","leads"]}'::jsonb,
    updated_at = NOW()
WHERE id = '074fc39c-f6ba-50a7-90da-f0fccfc4a20b'::uuid;
INSERT INTO marketplace_templates (
  id, slug, name, category, kind, pricing_tier, industry, description, version,
  thumbnail, icon, tags, author, status, price, is_public, is_featured,
  supports_agents, supports_domains, supports_billing, supports_mobile,
  package_path, install_count, default_config, created_at, updated_at
) VALUES (
  'f3b6bef2-b4c0-5050-80a1-0a42976cfc1f'::uuid,
  'ai-landing-starter',
  'AI Landing Page Starter',
  'landing'::template_category_enum,
  'package'::template_kind_enum,
  'free'::template_pricing_tier_enum,
  'growth',
  'Legacy alias of Landing Page Starter — high-converting landing with AI assistant.',
  '1.0.0',
  '/templates/landing.png',
  'sparkles',
  ARRAY['landing', 'conversion', 'demo', 'faq', 'package', 'legacy']::text[],
  'THTWAAT',
  'published'::template_status_enum,
  0,
  TRUE,
  FALSE,
  TRUE, TRUE, TRUE, FALSE,
  'apps/templates/landing',
  0,
  '{"stack":["nextjs15","tailwind","shadcn"],"env":["NEXT_PUBLIC_API_URL","NEXT_PUBLIC_AGENT_API_KEY"],"sections":["hero","ai_chat_cta","features","benefits","pricing","testimonials","faq","book_demo","contact"],"features":["widget","inline_assistant","streaming","leads"]}'::jsonb,
  NOW(), NOW()
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  kind = EXCLUDED.kind,
  pricing_tier = EXCLUDED.pricing_tier,
  industry = EXCLUDED.industry,
  description = EXCLUDED.description,
  thumbnail = EXCLUDED.thumbnail,
  icon = EXCLUDED.icon,
  tags = EXCLUDED.tags,
  author = EXCLUDED.author,
  status = EXCLUDED.status,
  is_public = EXCLUDED.is_public,
  is_featured = EXCLUDED.is_featured,
  supports_agents = EXCLUDED.supports_agents,
  supports_domains = EXCLUDED.supports_domains,
  supports_billing = EXCLUDED.supports_billing,
  supports_mobile = EXCLUDED.supports_mobile,
  package_path = EXCLUDED.package_path,
  default_config = EXCLUDED.default_config,
  updated_at = NOW()
  -- note: version column updated only by upgrade script / version insert
;
INSERT INTO marketplace_template_versions (
  id, template_id, version, changelog, config, is_latest, published_at, created_at, updated_at
) VALUES (
  gen_random_uuid(),
  'f3b6bef2-b4c0-5050-80a1-0a42976cfc1f'::uuid,
  '1.0.0',
  'Alias of landing-page-starter for backward compatibility',
  '{"stack":["nextjs15","tailwind","shadcn"],"env":["NEXT_PUBLIC_API_URL","NEXT_PUBLIC_AGENT_API_KEY"],"sections":["hero","ai_chat_cta","features","benefits","pricing","testimonials","faq","book_demo","contact"],"features":["widget","inline_assistant","streaming","leads"]}'::jsonb,
  TRUE,
  NOW(),
  NOW(),
  NOW()
)
ON CONFLICT (template_id, version) DO UPDATE SET
  changelog = EXCLUDED.changelog,
  config = EXCLUDED.config,
  is_latest = TRUE,
  published_at = COALESCE(marketplace_template_versions.published_at, NOW()),
  updated_at = NOW();

UPDATE marketplace_templates
SET version = '1.0.0',
    default_config = '{"stack":["nextjs15","tailwind","shadcn"],"env":["NEXT_PUBLIC_API_URL","NEXT_PUBLIC_AGENT_API_KEY"],"sections":["hero","ai_chat_cta","features","benefits","pricing","testimonials","faq","book_demo","contact"],"features":["widget","inline_assistant","streaming","leads"]}'::jsonb,
    updated_at = NOW()
WHERE id = 'f3b6bef2-b4c0-5050-80a1-0a42976cfc1f'::uuid;
INSERT INTO marketplace_templates (
  id, slug, name, category, kind, pricing_tier, industry, description, version,
  thumbnail, icon, tags, author, status, price, is_public, is_featured,
  supports_agents, supports_domains, supports_billing, supports_mobile,
  package_path, install_count, default_config, created_at, updated_at
) VALUES (
  '6b67097f-f837-58ab-be80-d7f767a3d59c'::uuid,
  'ai-saas-starter',
  'AI SaaS Starter',
  'saas'::template_category_enum,
  'package'::template_kind_enum,
  'free'::template_pricing_tier_enum,
  'b2b',
  'Legacy alias of SaaS Starter — full SaaS dashboard with agents and billing.',
  '1.0.0',
  '/templates/saas.png',
  'layout-dashboard',
  ARRAY['saas', 'dashboard', 'billing', 'auth', 'package', 'legacy']::text[],
  'THTWAAT',
  'published'::template_status_enum,
  0,
  TRUE,
  FALSE,
  TRUE, TRUE, TRUE, FALSE,
  'apps/templates/saas',
  0,
  '{"stack":["nextjs15","tailwind","tanstack-query","rhf","zod"],"env":["NEXT_PUBLIC_API_URL","NEXT_PUBLIC_AGENT_API_KEY"],"modules":["auth","dashboard","agents","knowledge","domains","billing","analytics","settings","marketplace"],"features":["jwt","otp","usage_meter","publish"]}'::jsonb,
  NOW(), NOW()
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  kind = EXCLUDED.kind,
  pricing_tier = EXCLUDED.pricing_tier,
  industry = EXCLUDED.industry,
  description = EXCLUDED.description,
  thumbnail = EXCLUDED.thumbnail,
  icon = EXCLUDED.icon,
  tags = EXCLUDED.tags,
  author = EXCLUDED.author,
  status = EXCLUDED.status,
  is_public = EXCLUDED.is_public,
  is_featured = EXCLUDED.is_featured,
  supports_agents = EXCLUDED.supports_agents,
  supports_domains = EXCLUDED.supports_domains,
  supports_billing = EXCLUDED.supports_billing,
  supports_mobile = EXCLUDED.supports_mobile,
  package_path = EXCLUDED.package_path,
  default_config = EXCLUDED.default_config,
  updated_at = NOW()
  -- note: version column updated only by upgrade script / version insert
;
INSERT INTO marketplace_template_versions (
  id, template_id, version, changelog, config, is_latest, published_at, created_at, updated_at
) VALUES (
  gen_random_uuid(),
  '6b67097f-f837-58ab-be80-d7f767a3d59c'::uuid,
  '1.0.0',
  'Alias of saas-starter for backward compatibility',
  '{"stack":["nextjs15","tailwind","tanstack-query","rhf","zod"],"env":["NEXT_PUBLIC_API_URL","NEXT_PUBLIC_AGENT_API_KEY"],"modules":["auth","dashboard","agents","knowledge","domains","billing","analytics","settings","marketplace"],"features":["jwt","otp","usage_meter","publish"]}'::jsonb,
  TRUE,
  NOW(),
  NOW(),
  NOW()
)
ON CONFLICT (template_id, version) DO UPDATE SET
  changelog = EXCLUDED.changelog,
  config = EXCLUDED.config,
  is_latest = TRUE,
  published_at = COALESCE(marketplace_template_versions.published_at, NOW()),
  updated_at = NOW();

UPDATE marketplace_templates
SET version = '1.0.0',
    default_config = '{"stack":["nextjs15","tailwind","tanstack-query","rhf","zod"],"env":["NEXT_PUBLIC_API_URL","NEXT_PUBLIC_AGENT_API_KEY"],"modules":["auth","dashboard","agents","knowledge","domains","billing","analytics","settings","marketplace"],"features":["jwt","otp","usage_meter","publish"]}'::jsonb,
    updated_at = NOW()
WHERE id = '6b67097f-f837-58ab-be80-d7f767a3d59c'::uuid;
COMMIT;
