-- AUTO-GENERATED by scripts/generate_marketplace_seed_sql.py
-- Generated: 2026-08-04T01:45:36Z
-- Rollback package starter seeds only (does not touch prompt catalog).
BEGIN;

DELETE FROM marketplace_template_favorites
WHERE template_id IN (
  '13612b59-e106-518d-9d6c-f1394612b33a'::uuid,
  '9c83f7bb-9e02-5419-94be-9dc54e128e9b'::uuid,
  'c7d0f642-b3e9-5be5-9f1d-d760a03017f1'::uuid,
  'abae812e-931c-5b03-90fd-d680f766b587'::uuid,
  'b90a85ba-ada6-5e5b-8f7c-5ff49b188c64'::uuid,
  '17c6ef3f-e40f-5768-b9e5-eeb55c3c5f4a'::uuid,
  '48291637-cabe-5931-9f7d-3fd850510fab'::uuid,
  'e5e0294c-8b8e-5109-b043-74ae80f47264'::uuid,
  '170835ca-adce-5eea-baf1-975233a820d4'::uuid,
  '074fc39c-f6ba-50a7-90da-f0fccfc4a20b'::uuid,
  'f3b6bef2-b4c0-5050-80a1-0a42976cfc1f'::uuid,
  '6b67097f-f837-58ab-be80-d7f767a3d59c'::uuid
);

DELETE FROM marketplace_template_installations
WHERE template_id IN (
  '13612b59-e106-518d-9d6c-f1394612b33a'::uuid,
  '9c83f7bb-9e02-5419-94be-9dc54e128e9b'::uuid,
  'c7d0f642-b3e9-5be5-9f1d-d760a03017f1'::uuid,
  'abae812e-931c-5b03-90fd-d680f766b587'::uuid,
  'b90a85ba-ada6-5e5b-8f7c-5ff49b188c64'::uuid,
  '17c6ef3f-e40f-5768-b9e5-eeb55c3c5f4a'::uuid,
  '48291637-cabe-5931-9f7d-3fd850510fab'::uuid,
  'e5e0294c-8b8e-5109-b043-74ae80f47264'::uuid,
  '170835ca-adce-5eea-baf1-975233a820d4'::uuid,
  '074fc39c-f6ba-50a7-90da-f0fccfc4a20b'::uuid,
  'f3b6bef2-b4c0-5050-80a1-0a42976cfc1f'::uuid,
  '6b67097f-f837-58ab-be80-d7f767a3d59c'::uuid
);

DELETE FROM marketplace_template_versions
WHERE template_id IN (
  '13612b59-e106-518d-9d6c-f1394612b33a'::uuid,
  '9c83f7bb-9e02-5419-94be-9dc54e128e9b'::uuid,
  'c7d0f642-b3e9-5be5-9f1d-d760a03017f1'::uuid,
  'abae812e-931c-5b03-90fd-d680f766b587'::uuid,
  'b90a85ba-ada6-5e5b-8f7c-5ff49b188c64'::uuid,
  '17c6ef3f-e40f-5768-b9e5-eeb55c3c5f4a'::uuid,
  '48291637-cabe-5931-9f7d-3fd850510fab'::uuid,
  'e5e0294c-8b8e-5109-b043-74ae80f47264'::uuid,
  '170835ca-adce-5eea-baf1-975233a820d4'::uuid,
  '074fc39c-f6ba-50a7-90da-f0fccfc4a20b'::uuid,
  'f3b6bef2-b4c0-5050-80a1-0a42976cfc1f'::uuid,
  '6b67097f-f837-58ab-be80-d7f767a3d59c'::uuid
);

DELETE FROM marketplace_templates
WHERE id IN (
  '13612b59-e106-518d-9d6c-f1394612b33a'::uuid,
  '9c83f7bb-9e02-5419-94be-9dc54e128e9b'::uuid,
  'c7d0f642-b3e9-5be5-9f1d-d760a03017f1'::uuid,
  'abae812e-931c-5b03-90fd-d680f766b587'::uuid,
  'b90a85ba-ada6-5e5b-8f7c-5ff49b188c64'::uuid,
  '17c6ef3f-e40f-5768-b9e5-eeb55c3c5f4a'::uuid,
  '48291637-cabe-5931-9f7d-3fd850510fab'::uuid,
  'e5e0294c-8b8e-5109-b043-74ae80f47264'::uuid,
  '170835ca-adce-5eea-baf1-975233a820d4'::uuid,
  '074fc39c-f6ba-50a7-90da-f0fccfc4a20b'::uuid,
  'f3b6bef2-b4c0-5050-80a1-0a42976cfc1f'::uuid,
  '6b67097f-f837-58ab-be80-d7f767a3d59c'::uuid
)
   OR slug IN (
  'ai-website-starter',
  'ecommerce-starter',
  'hotel-website-starter',
  'restaurant-starter',
  'portfolio-starter',
  'blog-starter',
  'saas-starter',
  'crm-starter',
  'documentation-site',
  'landing-page-starter',
  'ai-landing-starter',
  'ai-saas-starter'
);

COMMIT;
