"""
app/payments/invoices/model.py

SQLAlchemy model for Invoices generated by payment providers.
"""
import uuid
import enum
from sqlalchemy import Column, String, Numeric, Enum as SAEnum, ForeignKey, DateTime
from sqlalchemy.dialects.postgresql import UUID, JSONB
from app.models.base import Base, TimestampMixin


class InvoiceStatus(str, enum.Enum):
    DRAFT     = "draft"
    OPEN      = "open"
    PAID      = "paid"
    VOID      = "void"
    UNCOLLECTIBLE = "uncollectible"


class Invoice(Base, TimestampMixin):
    __tablename__ = "invoices"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True, nullable=False)

    company_id      = Column(UUID(as_uuid=True), ForeignKey("companies.id", ondelete="CASCADE"), nullable=False, index=True)
    subscription_id = Column(UUID(as_uuid=True), ForeignKey("subscriptions.id", ondelete="SET NULL"), nullable=True)

    # Provider data
    provider            = Column(String(50), nullable=False)  # stripe | razorpay | manual
    provider_invoice_id = Column(String(255), nullable=True, index=True, unique=True)
    provider_payment_id = Column(String(255), nullable=True)  # Stripe payment_intent or Razorpay payment_id

    # Financials
    amount_due  = Column(Numeric(10, 2), nullable=False)
    amount_paid = Column(Numeric(10, 2), nullable=False, default=0)
    currency    = Column(String(3), nullable=False, default="USD")
    status      = Column(SAEnum(InvoiceStatus, name="invoice_status_enum"), nullable=False, default=InvoiceStatus.OPEN)

    # Dates
    period_start = Column(DateTime(timezone=True), nullable=True)
    period_end   = Column(DateTime(timezone=True), nullable=True)
    due_date     = Column(DateTime(timezone=True), nullable=True)
    paid_at      = Column(DateTime(timezone=True), nullable=True)

    # PDF / hosted link
    invoice_pdf   = Column(String(1000), nullable=True)
    hosted_url    = Column(String(1000), nullable=True)
    invoice_metadata = Column(JSONB, nullable=True)

    def __repr__(self) -> str:
        return f"<Invoice id={self.id} amount={self.amount_paid}/{self.amount_due} status={self.status}>"
