"""Nginx virtual host generator for verified / live domains."""
from __future__ import annotations

import logging
from pathlib import Path
from typing import Optional

from app.config.settings import settings

logger = logging.getLogger(__name__)

VHOST_TEMPLATE = """\
# Auto-generated by THTWAAT Domain Manager — do not edit by hand
# domain: {hostname}

server {{
    listen 80;
    server_name {hostname}{www_alias};

    location ^~ /.well-known/acme-challenge/ {{
        root {webroot};
        default_type text/plain;
    }}

    location /health {{
        proxy_pass http://api_backend/live;
        proxy_set_header Host $host;
    }}

    location / {{
        return 301 https://$host$request_uri;
    }}
}}

server {{
    listen 443 ssl http2;
    server_name {hostname}{www_alias};

    ssl_certificate     {cert_path};
    ssl_certificate_key {key_path};
    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;
    ssl_ciphers HIGH:!aNULL:!MD5;

    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
    add_header X-Content-Type-Options nosniff always;
    add_header X-Frame-Options SAMEORIGIN always;
    add_header Referrer-Policy strict-origin-when-cross-origin always;

    client_max_body_size 50m;

    # Prometheus series are internal-only; never serve them from a tenant vhost.
    location = /metrics {{
        deny all;
    }}

    location / {{
        limit_req zone=api_limit burst=40 nodelay;
        proxy_pass http://api_backend;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_read_timeout 120s;
    }}
}}
"""


def conf_dir() -> Path:
    d = Path(getattr(settings, "NGINX_GENERATED_DIR", "nginx/conf.d/domains"))
    d.mkdir(parents=True, exist_ok=True)
    return d


def generate_vhost(
    hostname: str,
    cert_path: str,
    key_path: str,
    *,
    include_www: bool = False,
) -> Path:
    """Write nginx vhost for a custom domain. Returns config path."""
    out_dir = conf_dir()
    out_dir.mkdir(parents=True, exist_ok=True)
    webroot = str(Path(getattr(settings, "SSL_WEBROOT_DIR", "nginx/acme-webroot")).resolve()).replace("\\", "/")
    # Inside nginx container paths differ — use container paths when configured
    cert_c = getattr(settings, "NGINX_CERT_CONTAINER_PREFIX", None)
    if cert_c:
        # Map host-relative nginx/ssl/domains/X → /etc/nginx/ssl/domains/X
        rel = Path(cert_path).as_posix()
        if "nginx/ssl/" in rel:
            rel = rel.split("nginx/ssl/", 1)[1]
            cert_path = f"/etc/nginx/ssl/{rel}"
        key_rel = Path(key_path).as_posix()
        if "nginx/ssl/" in key_rel:
            key_rel = key_rel.split("nginx/ssl/", 1)[1]
            key_path = f"/etc/nginx/ssl/{key_rel}"
        webroot = "/var/www/acme"

    www_alias = f" www.{hostname}" if include_www and not hostname.startswith("www.") else ""
    content = VHOST_TEMPLATE.format(
        hostname=hostname,
        www_alias=www_alias,
        webroot=webroot,
        cert_path=Path(cert_path).as_posix(),
        key_path=Path(key_path).as_posix(),
    )
    out = out_dir / f"{hostname}.conf"
    out.write_text(content, encoding="utf-8")
    logger.info("nginx_vhost_written path=%s hostname=%s", out, hostname)
    return out


def remove_vhost(hostname: str) -> None:
    path = conf_dir() / f"{hostname}.conf"
    if path.exists():
        path.unlink()
        logger.info("nginx_vhost_removed hostname=%s", hostname)


def reload_nginx() -> tuple[bool, str]:
    """Best-effort nginx reload (docker exec or local nginx -s reload)."""
    import subprocess

    # Prefer docker compose nginx container
    for cmd in (
        ["docker", "compose", "exec", "-T", "nginx", "nginx", "-s", "reload"],
        ["nginx", "-s", "reload"],
    ):
        try:
            r = subprocess.run(cmd, capture_output=True, text=True, timeout=30)
            if r.returncode == 0:
                return True, "nginx reloaded"
        except Exception:
            continue
    return False, "nginx reload skipped (container/binary unavailable)"
